module.exports = [
  { repo: 'vercel/next.js', expectedType: 'framework' },
  { repo: 'facebook/react', expectedType: 'library' },
  { repo: 'vuejs/vue', expectedType: 'framework' },
  { repo: 'nestjs/nest', expectedType: 'framework' },
  { repo: 'axios/axios', expectedType: 'library' },
  { repo: 'lodash/lodash', expectedType: 'library' },
  { repo: 'cli/cli', expectedType: 'cli-tool' },
  { repo: 'yargs/yargs', expectedType: 'cli-tool' },
  { repo: 'microsoft/TypeScript', expectedType: 'language-tooling' },
  { repo: 'repoforge-dev/authority-layer', expectedType: 'analysis-tool' },
  { repo: 'openai/openai-python', expectedType: 'sdk' },
  { repo: 'langchain-ai/langchain', expectedType: 'ai-agent-framework' },
  { repo: 'huggingface/transformers', expectedType: 'ai-tooling' },
  { repo: 'pandas-dev/pandas', expectedType: 'library' },
  { repo: 'scikit-learn/scikit-learn', expectedType: 'library' },
  { repo: 'torvalds/linux', expectedType: 'system-project' },
  { repo: 'freeCodeCamp/freeCodeCamp', expectedType: 'learning-platform' },
  { repo: 'TheAlgorithms/Python', expectedType: 'learning-resource' },
];
